services:
    rc_server:
        image: ghcr.io/ncsuarc/arcdrop
        network_mode: "host"
        command: ros2 launch combined_launch.py
    microros_agent: 
        image: microros/micro-ros-agent:humble 
        network_mode: "host"
        volumes:
        - /dev:/dev
        - /dev/shm:/dev/shm
        privileged: true
        command: serial --dev /dev/tty_teensy -v6

