services:
    rc-server:
        container_name: rc-server
        image: ghcr.io/ncsuarc/arcdrop:latest
        network_mode: "host"
        command: ros2 launch arcdrop rc_server_launch.py
    micro-ros-agent: 
        container_name: micro-ros-agent
        image: microros/micro-ros-agent:humble 
        volumes:
        - /dev:/dev
        privileged: true
        command: serial --dev /dev/tty_teensy -v6
