services:
  mavros:
    container_name: mavros
    image: ghcr.io/ncsuarc/mavros
    command: ros2 run mavros mavros_node --ros-args -p fcu_url:="" -p gcs_url:=""
  mavp2p:
    container_name: mavp2p
    image: aler9/mavp2p
    volumes:
    - /dev:/dev
    privileged: true
    command: serial:/dev/tty_pixhawk:57600 udpc:0.0.0.0:14551
