services:
  mavros:
    container_name: mavros
    image: ghcr.io/ncsuarc/mavros
    network_mode: host
    command: ros2 run mavros mavros_node --ros-args -p fcu_url:="/dev/tty_pixhawk" -p gcs_url:="udp://localhost:14551@"
  mavp2p:
    container_name: mavp2p
    image: aler9/mavp2p
    network_mode: host
    volumes:
    - /dev:/dev
    privileged: true
    command: serial:/dev/tty_pixhawk:57600 udpc:localhost:14550 udpc:localhost:14551
