services:
  mavros:
    container_name: mavros
    image: ghcr.io/ncsuarc/mavros:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
    - 14551:14551
    command: ros2 run mavros mavros_node --ros-args -p fcu_url:="udp://localhost:14551@"
  mavp2p:
    container_name: mavp2p
    image: aler9/mavp2p
    restart: unless-stopped
    network_mode: host
    volumes:
    - /dev:/dev
    privileged: true
    command: serial:/dev/tty_pixhawk:57600 udpc:localhost:14550 udpc:localhost:14551
